trivial_reduction_omp:
	g++ -fopenmp -o trivial_reduction_omp trivial_reduction_omp.cpp 
	&& ./trivial_reduction_omp && rm trivial_reduction_omp

binary_reduction_omp:
	g++ -fopenmp -o binary_reduction_omp binary_reduction.cpp
	&& ./binary_reduction_omp && rm binary_reduction_omp
