trivial_reduction_mpi:
	mpic++ -o trivial_reduction_mpi
	 trivial_reduction_mpi.cpp && mpirun -np 4 trivial_reduction_mpi
	 && rm trivial_reduction_mpi

binary_reduction_mpi:
	mpic++ -o binary_reduction_mpi
	 binary_reduction_mpi.cpp && mpirun -np 4 binary_reduction_mpi
	  && rm binary_reduction_mpi
